CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE category (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    description VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    blocked_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);